name: emelins.co
favicon: null
layout_spectrum: 0.95665
typography_spectrum: 0.9027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0dbd5'
    - '#3c3733'
    - '#b9b8b3'
    - '#6a655f'
    - '#9c5230'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
